version: "3.3"
services:
  event-producer:
    build:
      context: .
      dockerfile: event-producer/Dockerfile
    depends_on:
      - "rabbitmq"
    entrypoint: bash -c "sleep 50 && python app/main.py"
    environment:
      RABBITMQ_URL: "rabbitmq"
      SPEED_FACTOR: "10"
      START_DATE: "2022-06-04 16:00:00"
      END_DATE: "2022-06-05 00:00:00"
    networks:
      - default
  airport-service:
    build:
      context: .
      dockerfile: ./airport-service/Dockerfile
    entrypoint: bash -c "sleep 50 && python app/init_database.py && uvicorn app.main:app --host 0.0.0.0"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres/postgres"
    networks:
      - default
    ports:
      - "8000:8000"
  flight-status-service:
    build:
      context: .
      dockerfile: flight-status-service/Dockerfile
    depends_on:
      - "rabbitmq"
    entrypoint: bash -c "sleep 50 && python app/init_database.py && uvicorn app.main:app --host 0.0.0.0 --port 8001"
    environment:
      RABBITMQ_URL: "rabbitmq"
      STREAM_DELAY_IN_SECS: "1"
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres/postgres"
    networks:
      - default
    ports:
      - "8001:8001"
  flight-service:
    build:
      context: .
      dockerfile: ./flight-service/Dockerfile
    entrypoint: bash -c "sleep 50 && python app/init_database.py && uvicorn app.main:app --host 0.0.0.0 --port 8002"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres/postgres"
    networks:
      - default
    ports:
      - "8002:8002"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:14.3-bullseye
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - default
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default:
