version: "3.3"
services:
  event-producer:
    build:
      context: .
      dockerfile: event-producer/Dockerfile
    depends_on:
      - "rabbitmq"
    entrypoint: bash -c "sleep 20 && python app/main.py"
    environment:
      RABBITMQ_URL: "rabbitmq"
      SPEED_FACTOR: "100"
    networks:
      - default
  airport-service:
    build:
      context: .
      dockerfile: ./airport-service/Dockerfile
    entrypoint: bash -c "sleep 20 && python app/init_database.py && uvicorn app.main:app --host 0.0.0.0"
    networks:
      - default
    ports:
      - "8000:8000"
  flight-status-service:
    build:
      context: .
      dockerfile: flight-status-service/Dockerfile
    depends_on:
      - "rabbitmq"
    entrypoint: bash -c "sleep 20 && uvicorn app.main:app --host 0.0.0.0 --port 8001"
    environment:
      RABBITMQ_URL: "rabbitmq"
    networks:
      - default
    ports:
      - "8001:8001"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default:
