# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-airport-service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --deploy --dev
      working-directory: airport-service
    - name: Test with pytest
      run: |
        pipenv run pytest
      working-directory: airport-service
